name: golangci-lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


permissions:
  contents: read
  pull-requests: read
  checks: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    concurrency:
      group: linting
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          working-directory: server
          only-new-issues: true
    